/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FormButton: typeof import('./../components/Form/Button.vue')['default']
    FormInput: typeof import('./../components/Form/Input.vue')['default']
    FormInputBox: typeof import('./../components/Form/InputBox.vue')['default']
    FormRequiredMark: typeof import('./../components/Form/RequiredMark.vue')['default']
    FormTextArea: typeof import('./../components/Form/TextArea.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    Link: typeof import('./../components/Link.vue')['default']
    NavigationSidebar: typeof import('./../components/Navigation/Sidebar.vue')['default']
    Page: typeof import('./../components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollNotifier: typeof import('./../components/ScrollNotifier.vue')['default']
    UserMeta: typeof import('./../components/User/Meta.vue')['default']
    UserPageSidebar: typeof import('./../components/User/Page/Sidebar.vue')['default']
    UserPermissions: typeof import('./../components/User/Permissions.vue')['default']
    UserRoles: typeof import('./../components/User/Roles.vue')['default']
  }
}
